version: '3'

services:
  mongodb:
    image: mongo:latest
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /opt/data/mongo_home:/data/db
    restart: always
  backend:
    image: "gotripe:${BUILD_VERSION}"
    depends_on: 
      - mongodb
    environment: 
      WAIT_HOSTS: mongodb:27017
    ports: 
      - 8080:8080
    