version: '3'

services:

  mongodb:
    image: mongo:latest
    hostname: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /opt/data/mongo_home:/data/db
    restart: always
  
  backend:
    image: "gotripe:${BUILD_VERSION}"
    depends_on: 
      - mongodb
    ports: 
      - 8080:8080
    environment:
      # STRIPE
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET= ${STRIPE_WEBHOOK_SECRET}
  # frontend:
  #   image: gotripe:client
  #   depends_on:
  #     - backend
  #   ports:
  #     - 80:80

